#define SHT41_I2C_ADDR_44 0x44

typedef enum {
    SHT4X_MEASURE_HIGH_PRECISION_TICKS_CMD_ID = 0xfd,
    SHT4X_MEASURE_MEDIUM_PRECISION_TICKS_CMD_ID = 0xf6,
    SHT4X_MEASURE_LOWEST_PRECISION_TICKS_CMD_ID = 0xe0,
    SHT4X_ACTIVATE_HIGHEST_HEATER_POWER_LONG_TICKS_CMD_ID = 0x39,
    SHT4X_ACTIVATE_HIGHEST_HEATER_POWER_SHORT_TICKS_CMD_ID = 0x32,
    SHT4X_ACTIVATE_MEDIUM_HEATER_POWER_LONG_TICKS_CMD_ID = 0x2f,
    SHT4X_ACTIVATE_MEDIUM_HEATER_POWER_SHORT_TICKS_CMD_ID = 0x24,
    SHT4X_ACTIVATE_LOWEST_HEATER_POWER_LONG_TICKS_CMD_ID = 0x1e,
    SHT4X_ACTIVATE_LOWEST_HEATER_POWER_SHORT_TICKS_CMD_ID = 0x15,
    SHT4X_SERIAL_NUMBER_CMD_ID = 0x89,
    SHT4X_SOFT_RESET_CMD_ID = 0x94,
} SHT4xCmdId;