name: Build AVR Project for ATmega328P

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install AVR toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-avr avr-libc binutils-avr
    
    - name: Verify toolchain installation
      run: |
        avr-gcc --version
        avr-objcopy --version
        avr-size --version
    
    - name: Compile project
      run: |
        # ATmega328P at 8MHz, 5V
        avr-gcc -Wall -Os -DF_CPU=8000000UL -mmcu=atmega328p -o garageThermostat.elf garageThermostat.ino
        avr-objcopy -O ihex -R .eeprom garageThermostat.elf garageThermostat.hex
        avr-size --format=avr --mcu=atmega328p garageThermostat.elf
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: avr-build
        path: |
          *.hex
          *.elf
        retention-days: 30
